### ISSUE TITLE
Delete the sport by service provider

### ISSUE THREAD

**Issue by anandateertha-dev** [BookMySport-com-Platform/Service-Provider-Place-Registration#10]
### Description:

In this the service provider is given an option to delete the sport by providing the sportId.

**Input taken from the service provider:**
1. Authenticatoin token
2. Sport id

Create a sepearate API-endpoint named "deletesport" and implement the logic.

**Comment by nkthis** [comment]
This feature will be implemented by NK

**Comment by nkthis** [comment]
The feature has been implemented #11
